### PR TITLE
Python 3

### PR DESCRIPTION
**Pull request by karel-brinda**
* Make NanoSim work both with Python 3 and Python 2. The main problems were:
    * dict_value vs. list
    * missing xrange
* Add a test (it can be executed by `make -C test`)
* Add a Travis configuration file
* Fix two minor bugs
* Ignore compiled Python files (*.pyc)

### CODE REVIEW

**Comment by karel-brinda** [comment]
Not finished yet, there are still some parts of the code which don't work with Python 3.

**Comment by cheny19** [comment]
Hi Karel,

I'm quite busy these days. When I have time, I'll look at your PR and merge them.

Thanks for helping me improving NanoSim!

Chen

**Comment by karel-brinda** [comment]
Hi Chen,

I finished this Python3 update. Please, could you add Travis testing to the main repository? I am currently running the tests only in my fork, see, e.g., https://travis-ci.org/karel-brinda/NanoSim/builds/202840562. As you can see, NanoSim works now with Python 2.6, 2.7, 3.2, 3.3., 3.4, 3.5 and 3.6 (before did not work with any Python 3.x).

Btw. I added NanoSim also to Bioconda (it can be installed by `conda install nanosim`) but the package is based on the old version. Once you merge all these pull requests, I will update this Bioconda package.

Karel

**Comment by cheny19** [comment]
Hi Karel,

I merged all commits related to Python 3 compatibility problem and other bugs. For the last commit, I have never met this problem myself, but I fixed it by randomly splitting `remainder` into two pieces (`head` and `tail`) if it's larger than any empirical value. 

For the commits you made about Travis, I didn't merge because I want the tool to be as simple as possible. I really appreciate your help with the test and maybe when I'm more familiar with Travis, I'll incorporate these changes.

Again, thanks a lot!

**Pull request closed without merging**
