### PR TITLE
Optimize transcriptome simulation

### PR DESCRIPTION
**Pull request by kmnip**
- consolidated code for progress updates for number of read simulated in metagenome/transcriptome/genome modes to a new method `check_print_progress`
- reduced frequency of writing updates to stdout, e.g. once every 10,000 reads simulated instead of 100
- optmized code for transcriptome simulation

Simulated 500,000 reads using 4 threads on the same machine for 3 trials:

| trial | before     | optimized | 
|-------|------------|-----------|
| 1     | 1h:00m:13s | ~~41m:42s~~ 16m:38s  |  
| 2     | 1h:12m:52s | ~~50m:47s~~ 16m:40s  | 
| 3     | 1h:03m:18s | ~~44m:53s~~ 16m:42s  | 

About ~75% reduction in **wallclock** runtime.

### CODE REVIEW

**Comment by kmnip** [comment]
I have further optimized the code in afe3cbe.

A new sample is only drawn from the KDE if the existing sample was previously used to simulate a read for the candidate transcript.

I have repeated my benchmarking trials on the same machine and updated the table above. The reduction in runtime is now ~75% (instead of ~30%)!

**Comment by kmnip** [comment]
Added a potential fix for #156

**Comment by SaberHQ** [comment]
> I have further optimized the code in [afe3cbe](https://github.com/bcgsc/NanoSim/commit/afe3cbea8d1af55cbddc0d72a6240c859d13cfb0).
> 
> A new sample is only drawn from the KDE if the existing sample was previously used to simulate a read for the candidate transcript.
> 
> I have repeated my benchmarking trials on the same machine and updated the table above. The reduction in runtime is now ~75% (instead of ~30%)!

This is really a neat and clever optimization @kmnip. Thanks for this. I also benchmarked it by simulating 1 million and 25 million read sets and I do confirm that it improved the runtime. I will add results here as well.

**Comment by SaberHQ** [comment]
Thank you @kmnip for the optimization and analysis. I also benchmarked it by simulating 1 million and 25 million reads using 38 threads on a same machine and the results demonstrates a reduction in wallclock runtime.

| Number of reads | before     | optimized | 
|-------|------------|-----------|
| 1 million     | 15m:56s |  10m:29s  |  
| 25 million    | 29h:46m:26s |  5h:34m:16s  |

**Comment by SaberHQ** [comment]
This pull request potentially fixes #159 and #131

**Review by SaberHQ — APPROVED** [review]

**Pull request merged**
